### ISSUE TITLE
Doesn't seem to work as of September

### ISSUE THREAD

**Issue by wefalltomorrow** [Maxhem2/instagram-mass-unsender#3]
After running the script it has one Unsend message pop up and after clicking Unsend it only deletes a single message, seems a bit weird.

**Comment by roshan-g20** [comment]
When putting the second code in console go to the middle part of the code there you'll find some timeouts are set to "3000" & one is somewhere near "300000"or so what you can do is instead of 3000 rewrite them as 1000 and the 300000 one write it as 500, it works on mine like this way and is fast enough, real hesitation is that it takes really very long time to reach upto the first message😅, and then due to low memory the browser reloads😭

**Comment by roshan-g20** [comment]
And also make sure all your adblockers are temporarily disabled during this process, and install and enable this extension during this process of you're on Chrome, https://chrome.google.com/webstore/detail/disable-content-security/ieelmcmcagommplceebfedjlakkhpden

**Comment by Maxhem2** [comment]
Thanks for the suggestions. Most issues should be addressed in the new Updated V2
- The timeouts do not have anything to do with @wefalltomorrow's issue
- I do not see where ad-blockers or Content Security could pose any issues
